server.port=8080
spring.main.allow-bean-definition-overriding=true
sample.docs.path=sample_couchbase_docs

couchbase.host=localhost
couchbase.bucket=sessiondb_billing
couchbase.username=mahesh
couchbase.password=admin123
